Increase buffer size to fix bufio.Scanner: token too long (#189)
* In actual use we are starting to see bufio.Scanner errors from the
analyzer

```
2024-08-06T12:50:15.653-0700    ERROR   analyze/analyzer.go:189 Error processing log file       {"path": "/Users/jlewi/.foyle/logs/raw/foyle.logs.2024-08-06T09:33:33.json", "error": "failed to scan file /Users/jlewi/.foyle/logs/raw/foyle.logs.2024-08-06T09:33:33.json: bufio.Scanner: token too long", "errorVerbose": "bufio.Scanner: token too long\nfailed to scan file /Users/jlewi/.foyle/logs/raw/foyle.logs.2024-08-06T09:33:33.json\ngithub.com/jlewi/foyle/app/pkg/analyze.readLinesFromOffset\n\t/Users/jlewi/git_foyle/app/pkg/analyze/reader.go:35\ngithub.com/jlewi/foyle/app/pkg/analyze.(*Analyzer).processLogFile\n\t/Users/jlewi/git_foyle/app/pkg/analyze/analyzer.go:203\ngithub.com/jlewi/foyle/app/pkg/analyze.(*Analyzer).handleLogFileEvents.func1\n\t/Users/jlewi/git_foyle/app/pkg/analyze/analyzer.go:188\ngithub.com/jlewi/foyle/app/pkg/analyze.(*Analyzer).handleLogFileEvents\n\t/Users/jlewi/git_foyle/app/pkg/analyze/analyzer.go:194\nruntime.goexit\n\t/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1222"}
```

This is because the buffer used by the Scanner limits the max token size
and the default buffer is smaller then our longest log lines.

Since we are potentially logging the entire markdown document, our log
lines can O(size of markdown file).

So to fix this we allocate a larger buffer.